### ISSUE TITLE
New Ammo Belts next_use_time incorrect in extdata?

### ISSUE THREAD

**Issue by Selindrile** [Windower/Resources#30]
I'm using this function to get items next use

https://pastebin.com/FpWJzMam (Can't get the formatting to work properly here.)

I think it's returning nil for .next_use_time, though I can't diagnose as much as I'd like as I don't own the items, so I may be wrong, trying to test through someone else, but they say:

`add_to_chat(217,get_item_next_use('Chrono Bullet Pouch').next_use_time)`

Gives them attempt to index a nil value.

**Comment by z16** [comment]
This is almost certainly unrelated to resources, the extdata library is a standalone Lua library that works with data sent directly from the server. Please reopen this issue on the Lua repository.

**Comment by Selindrile** [comment]
Ah sorry I thought extdata library was part of resources, my apologies.

**Comment by alphaONE2** [comment]
By the way, you can use three back-ticks (`` ``` ``) to mark code you can also include a language name after the first `` ``` `` to add syntax highlighting
````markdown
```lua
local foo = function(x)
    return x * x
end
```
````
will display as
```lua
local foo = function(x)
    return x * x
end
```

**Comment by Selindrile** [comment]
Ah so just like discord formatting, I was unaware GitHubs was the same, I only used the code button, which is a single back-tick, which as I know from discord is meant for single-line code stuff.
